name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target-archs: x86
          - os: windows-latest
            target-archs: x86

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Checkout AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild
      
      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild
    
      - name: Install library
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install -yq --no-install-recommends gcc-multilib g++-multilib
        shell: pwsh
      
      - name: Build extension
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          python ../configure.py --sm-path ../sourcemod
          ambuild

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: ${{github.workspace}}/build/package