name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        include:
          - os: ubuntu-18.04
            target-archs: x86
          - os: windows-2019
            target-archs: x86

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Checkout AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild

      - name: checkout sourcemod
        uses: actions/checkout@v2
        with:
          path: sourcemod
          repository: alliedmodders/sourcemod
          submodules: recursive

      - name: Install library
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install -yq --no-install-recommends gcc-multilib g++-multilib
        shell: pwsh

      - name: Build extension
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          python ../configure.py --enable-optimize --sm-path ${{github.workspace}}/sourcemod
          ambuild

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: ${{github.workspace}}/build/package